version: 2.1
jobs:
  install:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "yarn.lock" }}
      - run: yarn install --pure-lockfile --offline
      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .npm
            - .cache

  test:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn test


  lint:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint


  depcheck:
    docker:
      - image: circleci/node:10.15.0
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/

  e2e:
    docker:
      - image: cypress/base:10
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn pub
      - run: yarn e2e



workflows:
  version: 2.1
  build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - depcheck:
          requires:
            - install
      - e2e:
          requires:
            - install
