version: 2


jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.11.1


    steps:
      - checkout


      - restore_cache:
          key: deps-{{ checksum "yarn.lock" }}


      - run: yarn install --pure-lockfile --offline


      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules


      - run: yarn lint


      - run: yarn test


      - run: yarn depcheck


      - run: yarn e2e
          name: yarn e2e
          command: |
            yarn pub
            yarn e2e
